### Arnoldi iterations

This project deals with Krylov subspaces. They are used to find approximate solutions for high dimension linear algebra problems, notably useful in big data. Reduction is a key problem to reduce time computing for very large matrices pow algorithms. Finding eigenvalues and eigenvectors of those very large matrices is the key solution however it is not a simple task.

Arnoldi is analogue to Graham-Schmidt algorithm for similarity transformations to Hessenberg form (nearly triangular matrix). Similarly it can be stopped, leaving with a partial reduction of this form with A a m x m matrix, Q a nearly orthogonal matrix, H the Hessenberg form matrix.

\begin{equation}
A = Q H Q^{*}
\end{equation}

Let's tackle partial reduction with n first columns of AQ = QH with Qn the m x n matrix with  first n columns of Q. H in the next equation correspond to the upper-left (n+1) x n matrix extracted from H.

\begin{equation}
A Q_n = Q_{n+1} \tilde{H_n}
\end{equation}


In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
research_link_small = "https://www.cs.cmu.edu/afs/cs/academic/class/15859n-f16/Handouts/TrefethenBau/ArnoldiIteration-33.pdf"
research_link_p_262 = "http://mezbanhabibi.ir/wp-content/uploads/2020/01/NumericalLinearAlgebra-Lloyd-N1.-Trefethen-David-Bau.pdf"

In [3]:
def arnoldi(A,iterations):
    m = A[0].size
    Qn = np.zeros((m,iterations + 1)) 
    H = np.zeros((iterations + 1, iterations))
    b = np.random.randn(m)
    Qn[:,0] = b / np.linalg.norm(b)
    for n in range(iterations):
        v = A @ Qn[:,n]
        for j in range(n + 1):
            H[j,n] = Qn[:,j].conj().T @ v
            v -= H[j,n] * Qn[:,j]
        H[n+1,n] = np.linalg.norm(v)
        try : 
            Qn[:,n+1] = v / H[n+1,n]  
        except ZeroDivisionError : 
            return Qn, H
    Q = Qn[:, :iterations]
    H = H[:iterations, :]
    return Q,H

Qn columns {qj} form orthonormal bases for successive Krylov subspaces
H is the upper Hessenberg matrice

In [4]:
m = 6
A = np.random.randint(0,100,(m,m))
Q, H = arnoldi(A,m)
arnoldi_result = (Q @ H @ Q.conj().T).astype(int)
print(arnoldi_result == A, '\n')
print(A, '\n')
print(arnoldi_result)

[[False False  True False  True  True]
 [False  True False False False False]
 [False False  True False  True False]
 [False  True  True False  True False]
 [ True False False False False  True]
 [False False  True False  True  True]] 

[[70 48 69 72  3 84]
 [41 31 21 86 18 63]
 [80 50 44 53 61 48]
 [62 21 30 35 52 69]
 [ 5 63  5 61  4 65]
 [16  7 76 48 29 93]] 

[[69 47 69 71  3 84]
 [40 31 20 85 17 62]
 [79 49 44 52 61 47]
 [61 21 30 34 52 68]
 [ 5 62  4 60  3 65]
 [15  6 76 47 29 93]]


In [20]:
def Graham_Schmidt(A):
    n = A[0].size
    v = np.zeros((n,n))
    r, q = np.zeros((n,n)), np.zeros((n,n))
    for i in range(n):
        v[:,i] = A[:,i]
    for i in range(n):
        r[i,i] = np.linalg.norm(v[:,i])
        q[:,i] = v[:,i] / r[i,i]
        for j in range(i + 1, n):
            r[i,j] = q[:,i].conj().T @ v[:,j]
            v[:,j] -= r[i,j] * q[:,i]
            
    return q, r
        
        

m = 10
A = np.random.randint(0,100,(m,m))
q,r = Graham_Schmidt(A)

print(A, '\n')
print((q @ r).astype(int))
print(q)
print(r)

[[68 88 75 30 93 90 19 66 16 95]
 [94 20 49  6 72 21 76 73 94 83]
 [ 7 94  2 22 59 86 30  8 90 41]
 [75 89 28 61 48  1 33 23 64 51]
 [92 90  5 48 60 72  1 88 52 39]
 [15 21 30 24 89 57 31  3 17 75]
 [15 68 99 23 17 97 54 24 26 67]
 [59 96 42 41 34  8 62 30 46  5]
 [28  9 30 40 74 12 89  6 55 33]
 [ 8 84  6 21 13 22  3 90 83 21]] 

[[68 88 75 30 92 90 19 66 16 94]
 [94 19 49  6 71 21 76 73 94 83]
 [ 7 94  1 22 58 86 29  7 90 41]
 [75 89 27 61 48  0 33 22 64 51]
 [92 90  5 48 59 72  1 88 51 39]
 [15 21 30 24 89 57 31  3 17 74]
 [15 68 99 22 17 97 53 23 26 67]
 [59 96 42 41 34  8 62 29 46  5]
 [28  9 30 39 74 12 89  6 55 32]
 [ 8 84  6 21 12 22  2 89 83 21]]
[[ 0.37791194  0.14244412  0.30806391 -0.23100526  0.26990538 -0.04672161
  -0.58948495 -0.04984778 -0.21241691 -0.46743488]
 [ 0.52240768 -0.45967904  0.14371123 -0.43588712  0.16957873 -0.19474533
   0.36166088  0.11447482  0.28667168  0.11121364]
 [ 0.0389027   0.56333916 -0.21665529 -0.14881248  0.47227737  0.09383507
   0.4156362