### Arnoldi iterations

This project deals with Krylov subspaces. They are used to find approximate solutions for high dimension linear algebra problems, notably useful in big data. Reduction is a key problem to reduce time computing for very large matrices pow algorithms. Finding eigenvalues and eigenvectors of those very large matrices is the key solution however it is not a simple task.

Arnoldi is analogue to Graham-Schmidt algorithm for similarity transformations to Hessenberg form. Similarly it can be stopped, leaving with a partial reduction of this form with A a m x m matrix.

\begin{equation}
A = Q H Q^{*}
\end{equation}

Let's tackle partial reduction with n first columns of AQ = QH with Qn the m x n matrix with  first n columns of Q. 

\begin{equation}
A Q_n = Q_{n+1} \tilde{H_n}
\end{equation}


In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
research_link_small = "https://www.cs.cmu.edu/afs/cs/academic/class/15859n-f16/Handouts/TrefethenBau/ArnoldiIteration-33.pdf"
research_link_p_262 = "http://mezbanhabibi.ir/wp-content/uploads/2020/01/NumericalLinearAlgebra-Lloyd-N1.-Trefethen-David-Bau.pdf"

In [18]:
def arnoldi(A,iterations):
    m = A[0].size
    Qn = np.zeros((m,iterations + 1)) 
    H = np.zeros((iterations + 1, iterations))
    b = np.random.randn(m)
    Qn[:,0] = b / np.linalg.norm(b)
    for n in range(iterations):
        v = A @ Qn[:,n]
        for j in range(n + 1):
            H[j,n] = Qn[:,j].conj().T @ v
            v -= H[j,n] * Qn[:,j]
        H[n+1,n] = np.linalg.norm(v)
        try : 
            Qn[:,n+1] = v / H[n+1,n]  
        except ZeroDivisionError : 
            return Qn, H
    Q = Qn[:, :iterations]
    H = H[:iterations, :]
    return Q,H

Qn columns {qj} form orthonormal bases for successive Krylov subspaces
H is the upper Hessenberg matrice

In [19]:
m = 6
A = np.random.randint(0,100,(m,m))
Q, H = arnoldi(A,m)
arnoldi_result = (Q @ H @ Q.conj().T).astype(int)
print(arnoldi_result == A, '\n')
print(A, '\n')
print(arnoldi_result)

[[ True  True False False  True False]
 [ True  True False False False False]
 [ True  True False False  True False]
 [ True  True False  True  True False]
 [ True  True False False  True False]
 [ True  True False False  True False]] 

[[19 97 57 88 14 97]
 [53 47 11 58 53 84]
 [62 74 86 61 46 46]
 [80 32 77 84 84 65]
 [ 9  4 50 21 99 52]
 [ 7  9 12 52 26 92]] 

[[19 97 56 87 14 96]
 [53 47 10 57 52 83]
 [62 74 85 60 46 45]
 [80 32 76 84 84 64]
 [ 9  4 49 20 99 51]
 [ 7  9 11 51 26 91]]
